### ISSUE TITLE
Promise.finally() doesn't exist in Atom's JS runtime

### ISSUE THREAD

**Issue by sethfitz** [stamen/atom-cartodb#14]
**Atom Version**: 1.1.0
**System**: Mac OS X 10.11.1
**Thrown From**: [cartodb](https://github.com/stamen/atom-cartodb) package, v0.7.2
### Stack Trace

Uncaught TypeError: this.projectFile.read(...).then(...).then(...).then(...).then(...).catch(...).finally is not a function

```
At /Users/seth/.atom/packages/cartodb/lib/cartodb-preview-view.js:111

TypeError: this.projectFile.read(...).then(...).then(...).then(...).then(...).catch(...).finally is not a function
  at CartodbPreviewView.projectDidChange (/Users/seth/.atom/packages/cartodb/lib/cartodb-preview-view.js:141:20)
  at CartodbPreviewView.attached (/Users/seth/.atom/packages/cartodb/lib/cartodb-preview-view.js:181:12)
  at space-pen-div.View.element.attached (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:164:63)
  at space-pen-div.CustomElementPrototype.attachedCallback (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:51:55)
  at atom-pane.PaneElement.activeItemChanged (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-element.js:131:24)
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
  at Pane.module.exports.Pane.setActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:247:22)
  at Pane.module.exports.Pane.addItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:345:14)
  at Pane.module.exports.Pane.activateItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:310:14)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:474:16
```

**Comment by sethfitz** [comment]
https://github.com/stamen/atom-cartodb/blob/master/lib/cartodb-preview-view.js#L111-L113

The `Promise` implementation shipped with Atom-1.1 (Babel?) doesn't include `finally`.
